"""Add links to academic_work

Revision ID: 366563ea21c8
Revises: 6a3ebf78fe8f
Create Date: 2025-01-19 22:35:28.623717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '366563ea21c8'
down_revision: Union[str, None] = '6a3ebf78fe8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_works', sa.Column('links', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('academic_works', 'links')
    # ### end Alembic commands ###
