"""Add academic_works table

Revision ID: 45fc6c1c4f78
Revises: ec90e3bde6d2
Create Date: 2025-01-15 14:28:39.989413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45fc6c1c4f78'
down_revision: Union[str, None] = 'ec90e3bde6d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
