"""Add llm_keyword, llm_phrase and llm_extended_summary columns

Revision ID: 6a3ebf78fe8f
Revises: a876529d06b7
Create Date: 2025-01-17 22:58:24.959458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a3ebf78fe8f'
down_revision: Union[str, None] = 'a876529d06b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_works', sa.Column('llm_keywords', sa.String(), nullable=True))
    op.add_column('academic_works', sa.Column('llm_phrase', sa.String(), nullable=True))
    op.add_column('academic_works', sa.Column('llm_extended_summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('academic_works', 'llm_extended_summary')
    op.drop_column('academic_works', 'llm_phrase')
    op.drop_column('academic_works', 'llm_keywords')
    # ### end Alembic commands ###
