"""Initial migration

Revision ID: 9c9343728afe
Revises: 
Create Date: 2025-01-15 11:04:02.129156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c9343728afe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('hypothesises',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('extracted_topics', sa.JSON(), nullable=False),
    sa.Column('extracted_terms', sa.JSON(), nullable=False),
    sa.Column('extracted_entities', sa.JSON(), nullable=True),
    sa.Column('query_type', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['hypothesises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypothesises_id'), 'hypothesises', ['id'], unique=False)
    op.create_index(op.f('ix_hypothesises_user_id'), 'hypothesises', ['user_id'], unique=False)
    op.create_table('hypothesis_feedback',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('hypothesis_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypothesises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypothesis_feedback_hypothesis_id'), 'hypothesis_feedback', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_hypothesis_feedback_id'), 'hypothesis_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_hypothesis_feedback_user_id'), 'hypothesis_feedback', ['user_id'], unique=False)
    op.create_table('validation_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hypothesis_id', sa.String(), nullable=False),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('motivation', sa.String(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypothesises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_results_hypothesis_id'), 'validation_results', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_validation_results_id'), 'validation_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_results_id'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_hypothesis_id'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_hypothesis_feedback_user_id'), table_name='hypothesis_feedback')
    op.drop_index(op.f('ix_hypothesis_feedback_id'), table_name='hypothesis_feedback')
    op.drop_index(op.f('ix_hypothesis_feedback_hypothesis_id'), table_name='hypothesis_feedback')
    op.drop_table('hypothesis_feedback')
    op.drop_index(op.f('ix_hypothesises_user_id'), table_name='hypothesises')
    op.drop_index(op.f('ix_hypothesises_id'), table_name='hypothesises')
    op.drop_table('hypothesises')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
