"""Add llm_summary column

Revision ID: a876529d06b7
Revises: 512f0524b30f
Create Date: 2025-01-15 23:23:33.266247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a876529d06b7'
down_revision: Union[str, None] = '512f0524b30f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_works', sa.Column('llm_summary', sa.String(), nullable=True))
    op.add_column('academic_works', sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('academic_works', 'date_updated')
    op.drop_column('academic_works', 'llm_summary')
    # ### end Alembic commands ###
